"""add profile fields

Revision ID: 12a87197fa9a
Revises: efefabb83ce2
Create Date: 2025-09-15 17:16:29.686286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a87197fa9a'
down_revision = 'efefabb83ce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('cpf', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('education', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('profession', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('company', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('company')
        batch_op.drop_column('profession')
        batch_op.drop_column('education')
        batch_op.drop_column('cpf')
        batch_op.drop_column('address')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###
