"""add oauth fields

Revision ID: 4577647fee9c
Revises: 12a87197fa9a
Create Date: 2025-09-15 20:25:07.568654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4577647fee9c'
down_revision = '12a87197fa9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('oauth_sub', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_oauth_provider'), ['oauth_provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_oauth_sub'), ['oauth_sub'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_oauth_sub'))
        batch_op.drop_index(batch_op.f('ix_users_oauth_provider'))
        batch_op.drop_column('oauth_sub')
        batch_op.drop_column('oauth_provider')

    # ### end Alembic commands ###
