"""user models

Revision ID: b71a9c0a7b9c
Revises: 4577647fee9c
Create Date: 2025-09-15 21:43:47.335690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b71a9c0a7b9c'
down_revision = '4577647fee9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('expr', sa.Text(), nullable=False),
    sa.Column('params', sa.Text(), nullable=False),
    sa.Column('vars_list', sa.Text(), nullable=True),
    sa.Column('init_kind', sa.String(length=10), nullable=True),
    sa.Column('init_values', sa.Text(), nullable=True),
    sa.Column('solver', sa.String(length=10), nullable=True),
    sa.Column('maxfev', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_model_per_user')
    )
    with op.batch_alter_table('user_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_models_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_models_user_id'))

    op.drop_table('user_models')
    # ### end Alembic commands ###
